version: '3.4'

services:
  semanticbackend:
    image: semanticbackend
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
